In [1]:
import numpy as np

list = [12.23, 13.32, 100, 36.32]
arr = np.array(list)
arr

array([ 12.23,  13.32, 100.  ,  36.32])

In [3]:
import numpy as np

list = [[2,3,4],[5,6,7],[8,9,10]]
arr = np.array(list)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
import numpy as np
x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [7]:
import numpy as np
x = [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37]
reverse = np.flip(x)
reverse

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [8]:
import numpy as np
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [11]:
import numpy as np
x = [10, 20, 30]
x = np.append(x, [40, 50, 60, 70, 80, 90])
print(x)

[10 20 30 40 50 60 70 80 90]


In [14]:
import numpy as np
x = np.sqrt([1.00000000+0.j])
y = np.sqrt([0.70710678+0.70710678j])
print(x.real)
print(x.imag)
print(y.real)
print(y.imag)

[1.]
[0.]
[0.92387953]
[0.38268343]


In [15]:
import numpy as np
x = np.array([1,2,3])
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  4
Total bytes consumed by the elements of the array:  12


In [18]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]


In [19]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]
np.setdiff1d(array1, array2)

array([ 0, 20, 60, 80])

In [21]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))

[False False]
[False False]
[ True  True]
[ True  True]


In [6]:
  #15. Write a Python program to save a NumPy array to a text file
import numpy as np
List = [1, 2, 3, 4, 5]
Array = np.array(List)
print('Array:\n', Array)
np.savetxt("file1.txt", Array)
 
# Saving the array in a text file
content = np.loadtxt("file1.txt")
 
print("\nContent in file1.txt:\n", content)

Array:
 [1 2 3 4 5]

Content in file1.txt:
 [1. 2. 3. 4. 5.]


In [10]:
#16. Write a Python program to create a contiguous flattened array. 
import numpy as np
x = [[10,20,30],[20,40,50]]
array = np.array(x)
y = np.ravel(array)
y

array([10, 20, 30, 20, 40, 50])

In [11]:
#17. Write a Python program to change the data type of an array. 
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [15]:
#18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
import numpy as np
x = np.eye(3, dtype = int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
#19. Write a Python program to create an array which looks like below array.
import numpy as np
x = np.tri(4,3,-1)
x

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [21]:
#20. Write a Python program to concatenate two 2-dimensional arrays.
import numpy as np
x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])
z = np.concatenate((x,y),1)
z

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [25]:
#21. Write a Python program to make an array immutable (read-only).
import numpy as np
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1
x

ValueError: assignment destination is read-only

In [30]:
#22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.
import numpy as np
x = np.arange(0,12).reshape(3,4)
y = x * 3
y

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [33]:
#23. Write a Python program to convert a NumPy array into Python list structure.
import numpy as np
x = np.arange(0,6).reshape(3,2)
y = x.tolist()
y

[[0, 1], [2, 3], [4, 5]]

In [39]:
#23. Write a Python program to convert a NumPy array into Python list structure.
import numpy as np
x = np.array([0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,0.35399976,0.99469633,0.0694458,0.54711478])
np.set_printoptions(precision=3)
x

array([0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069,
       0.547])

In [41]:
#25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.
import numpy as np
x = np.array([1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
np.set_printoptions(suppress=3)
x

array([   0.   ,    1.6  , 1200.   ,    0.235])

In [48]:
#26. Write a Python program to how to add an extra column to an numpy array.
import numpy as np
x = np.array([[10,20,30],[40,50,60]])
y = np.array([[100],[200]])
np.append(x,y,axis = 1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [49]:
#27. Write a Python program to remove specific elements in a numpy array. 
import numpy as np
x = np.array([10,20,30,40,50,60,70,80,90,100])
index = [0,3,4]
y = np.delete(x, index)
y

array([ 20,  30,  60,  70,  80,  90, 100])